name       : libmnl
version    : 1.0.4
release    : 1
source     :
    - git|http://git.netfilter.org/libmnl : libmnl-1.0.4
license    : GPL-2.0 # CHECK ME
component  : programming
summary    : libmnl is a minimalistic user-space library oriented to Netlink developers
description: |
    libmnl is a minimalistic user-space library oriented to Netlink developers
builddeps  :
    - gcc
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
