name       : libmnl
version    : 1.0.4
release    : 3
source     :
    - https://netfilter.org/projects/libmnl/files/libmnl-1.0.4.tar.bz2 : 171f89699f286a5854b72b91d06e8f8e3683064c5901fb09d954a9ab6f551f81
license    : LGPL-2.1-or-later
component  : programming.library
summary    : libmnl is a minimalistic user-space library oriented to Netlink developers
description: |
    libmnl is a minimalistic user-space library oriented to Netlink developers. There are a lot of common tasks in parsing, validating, constructing of both the Netlink header and TLVs that are repetitive and easy to get wrong. This library aims to provide simple helpers that allows you to re-use code and to avoid re-inventing the wheel.
emul32     : yes
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
